{% set name = "python-lmdb" %}
{% set pypi_name = "lmdb" %}
{% set github_name = "py-lmdb" %}
{% set version = "0.92" %}
{% set sha256 = "e3eaf5f4a4d0fbae9c99bc803c21f91636c2c68dfd42ab1d58284ba4883695fb" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ github_name }}_{{ version }}.zip
  url: https://github.com/dw/{{ github_name }}/archive/{{ github_name }}_{{ version }}.zip
  sha256: {{ sha256 }}
  patches:
    - windows-skip-tests.patch

build:
  number: 1000
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
  run:
    - python

test:
  source_files:
    - tests
  requires:
    - pytest
  imports:
    - lmdb
  commands:
    - py.test tests

about:
  home: https://lmdb.readthedocs.io/
  license: OpenLDAP
  license_file: LICENSE
  summary: "Universal Python binding for the LMDB 'Lightning' Database"

  description: |
    LMDB is a fast, memory-efficient, embedded key-value store (it does
    not require running an external daemon).
    With memory-mapped files, it has the read performance of a pure
    in-memory database while retaining the persistence of standard
    disk-based databases.
    python-lmdb is a Python binding for LMDB including a bundled
    version of LMDB.
  doc_url: https://lmdb.readthedocs.io/
  dev_url: https://github.com/dw/py-lmdb/

extra:
  recipe-maintainers:
    - pitrou
