{% set version = "1.6.2" %}

package:
  name: python-lmdb
  version: {{ version }}

source:
  url: https://github.com/jnwatson/py-lmdb/archive/refs/tags/py-lmdb_{{ version }}.tar.gz
  sha256: 992fc8a5511d7c84a1ab6889d0d2ff957d452a00fc87167a6dc36ba42903b519

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - patch     # [unix]
  host:
    - python
    - setuptools
    - patch-ng  # [win]
    - pip
  run:
    - python

test:
  source_files:
    - tests
  requires:
    - pytest
  imports:
    - lmdb
  commands:
    - pytest tests

about:
  home: https://lmdb.readthedocs.io/
  license: OLDAP-2.8
  license_file: LICENSE
  summary: Universal Python binding for the LMDB 'Lightning' Database

  description: |
    LMDB is a fast, memory-efficient, embedded key-value store (it does
    not require running an external daemon).
    With memory-mapped files, it has the read performance of a pure
    in-memory database while retaining the persistence of standard
    disk-based databases.
    python-lmdb is a Python binding for LMDB including a bundled
    version of LMDB.
  doc_url: https://lmdb.readthedocs.io/
  dev_url: https://github.com/jnwatson/py-lmdb

extra:
  recipe-maintainers:
    - pitrou
    - h-vetinari
    - xhochy
