appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: BzQezJ7t9/FAbpn15/spFt7It8Ts67N7nwIYmzsScam4Fnqt/TA9FljJyIUQvGMe0gXGz/pXw9OEK9TkWDUGf2ajXfHzdTeSS+tjokF0BRL7xnZSHoMlBC8oatFzE7K4Ih+9cL/xjmPrIAU2M0SrnYRX463dcXNl3hAtf4gG8Qdj6pzLhQ2M8olEH0dE6iW8UtCC2mqbSCDmI/jpq+ZdipKhbFxjfpg21+YKLBxYRiAcGiffc9B1dHvEuApTLMlhBF0eWpjVbii/f21M6kVnHgBgBdXRjvFyyJv4gSqf9q2z5jd6YGtHI4UIQL5cgTbizFapOrUQHadAKrHTjTDEqga4NLoG8UCfLdtiGs8BDAVxeJevP0gfD6Y4FWcmMt6FiGZX6HE8GAyldhqtYQJNaJVexs9gbqCpAuO6/ngk33weQ0pXJcZRlQj20nrmz7QgRGeBBTCD4bHMGq9MhW7qc0DAeBcfPEowLoq0sBXIAy0pMi80oVNtBaeD2+N4OOOWk42Cw0Md2sUgwkSffmxWBiBHui7tK894q7lj6DuacYA+41jd96BKp3ekJQQcFTL+t4YX6h9LIcak75ifx4HRf4sq0MTlLsjsApH3aBzATZDNKpGWyggMyXMReQYFsb//K9TmydSSMOm7tMWJCe9uUBbeksqIdW45xAnkxeuMYbs=}
provider:
  win: azure
conda_forge_output_validation: true
